---
name: Build Stage
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"
      - name: Install dependencies
        run: npm ci
        working-directory: application/riser-chat-ui
      - name: Run Test Unit
        run: npm run test:unit
        working-directory: application/riser-chat-ui
